### ISSUE TITLE
Permission denied -- can't start server.

### ISSUE THREAD

**Issue by ghost** [eddyerburgh/react-boilerplate#1]
Cloned and `npm install` & `npm run dev` and got:

> react-boilerplate/node_modules/.bin/webpack-dev-server: Permission denied

Trying to figure out why...

**Comment by eddyerburgh** [comment]
Hey, so the problem is that you don't have permission to read/ execute the file.

I think this is because I included the node_modules that I originally downloaded to my PC.

I've removed node_modules from the repo. If you download again, `npm install` and then `npm run dev`, it should work.
