### ISSUE TITLE
Error while runnign "npm run dev"

### ISSUE THREAD

**Issue by pkumar01** [eddyerburgh/react-boilerplate#3]
When i tried npm run dev it gave me error "events.js:160 throw er; // Unhandled 'error' event".

Could you please help.

**Comment by eddyerburgh** [comment]
Hi, this error (EADDRINUSE) means the port webpack-dev-server is trying to run on is already in use by another program.

To fix this you can defineda different port for wbepack-dev-server to use on when you run npm run dev :

```
npm run dev -- --port 9888
```

This should get the server started on localhost:9887.

The number after --port is arbitrary. You can use any number you like as long as the port is free.

**Comment by eddyerburgh** [comment]
@pkumar01 did that resolve your issue?

**Comment by pkumar01** [comment]
Hey Eddy,

Sorry was busy on other things forgot to reply, yeah that fixed my issue. Thanks a lot for help.
